# Generated by Django 3.2.4 on 2021-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_auto_20210620_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='imageskat/'),
        ),
    ]
